/**
 * Script to expand marketplace mock data
 * Generates 70+ items, 12 PRs, and 20 POs for comprehensive testing
 */

import { writeFileSync, readFileSync } from 'fs';
import { join } from 'path';

// Read the original file to preserve headers
const originalFile = readFileSync(
  join(__dirname, '../src/data/marketplaceMockData.ts'),
  'utf-8'
);

// Extract the part before mockMarketplaceItems
const beforeItems = originalFile.substring(0, originalFile.indexOf('export const mockMarketplaceItems'));

// Generate 70+ comprehensive items
const items = `export const mockMarketplaceItems: MarketplaceItem[] = [
  // ========== FASTENERS CATEGORY (15 items) ==========
  {
    item_id: 'ITEM-FAST-001',
    item_code: 'BLT-HEX-M8',
    item_name: 'BAUT HEXAGON SOCKET M8 x 30mm',
    item_description: 'Hexagon socket head cap screw M8 x 30mm, carbon steel grade 8.8, black oxide finish',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 4500,
    currency: 'IDR',
    stock_quantity: 15000,
    lead_time_days: 3,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 200,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-002',
    item_code: 'BLT-HEX-M12',
    item_name: 'BAUT HEXAGON SOCKET M12 x 50mm',
    item_description: 'Hexagon socket head cap screw M12 x 50mm, stainless steel A4-70 for high temperature applications',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 12500,
    currency: 'IDR',
    stock_quantity: 5000,
    lead_time_days: 7,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 100,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-003',
    item_code: 'BLT-HEX-M20',
    item_name: 'BAUT HEXAGON SOCKET M20 x 80mm',
    item_description: 'Heavy-duty hexagon socket head cap screw M20 x 80mm, alloy steel grade 10.9 for critical applications',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 28000,
    currency: 'IDR',
    stock_quantity: 2000,
    lead_time_days: 10,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 50,
    warranty_months: 18,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-004',
    item_code: 'BLT-NUT-M10',
    item_name: 'BAUT DAN MUR SET M10',
    item_description: 'Complete bolt and nut set M10 x 40mm with washers, carbon steel grade 8.8, zinc plated',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 15000,
    currency: 'IDR',
    stock_quantity: 5000,
    lead_time_days: 5,
    unit_of_measure: 'SET',
    minimum_order_quantity: 100,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-005',
    item_code: 'BLT-NUT-M16',
    item_name: 'BAUT DAN MUR SET M16',
    item_description: 'Bolt and nut set M16 x 60mm, stainless steel 304, includes hex bolt, hex nut, flat and spring washers',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 28000,
    currency: 'IDR',
    stock_quantity: 2500,
    lead_time_days: 10,
    unit_of_measure: 'SET',
    minimum_order_quantity: 50,
    warranty_months: 24,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-006',
    item_code: 'BLT-NUT-M24',
    item_name: 'BAUT DAN MUR SET M24',
    item_description: 'Heavy-duty bolt and nut set M24 x 100mm, grade 10.9, hot-dip galvanized for structural applications',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 52000,
    currency: 'IDR',
    stock_quantity: 1500,
    lead_time_days: 14,
    unit_of_measure: 'SET',
    minimum_order_quantity: 25,
    warranty_months: 18,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-007',
    item_code: 'BLT-SP-TI',
    item_name: 'BAUT DAN MUR JENIS KHUSUS - Titanium',
    item_description: 'Special titanium alloy Ti-6Al-4V bolt and nut set M16 x 60mm for aerospace-grade turbine applications',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 385000,
    currency: 'IDR',
    stock_quantity: 300,
    lead_time_days: 28,
    unit_of_measure: 'SET',
    minimum_order_quantity: 10,
    warranty_months: 36,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-008',
    item_code: 'BLT-SP-INCONEL',
    item_name: 'BAUT DAN MUR JENIS KHUSUS - Inconel 625',
    item_description: 'High-temperature resistant Inconel 625 bolt and nut set M20 x 80mm for extreme conditions up to 1093°C',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 625000,
    currency: 'IDR',
    stock_quantity: 150,
    lead_time_days: 35,
    unit_of_measure: 'SET',
    minimum_order_quantity: 5,
    warranty_months: 36,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-009',
    item_code: 'BLT-ANCHOR-M16',
    item_name: 'BAUT JENIS KHUSUS - Anchor Bolt M16',
    item_description: 'Chemical anchor bolt M16 x 300mm with expansion sleeve for concrete mounting, load capacity 15kN',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 45000,
    currency: 'IDR',
    stock_quantity: 2000,
    lead_time_days: 10,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 50,
    warranty_months: 18,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-010',
    item_code: 'BLT-ANCHOR-M24',
    item_name: 'BAUT JENIS KHUSUS - Anchor Bolt M24',
    item_description: 'Heavy-duty anchor bolt M24 x 500mm with expansion sleeve for concrete foundation mounting, 30kN capacity',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 89000,
    currency: 'IDR',
    stock_quantity: 1000,
    lead_time_days: 14,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 50,
    warranty_months: 18,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-011',
    item_code: 'NUT-HEX-M12',
    item_name: 'MUR HEXAGON M12',
    item_description: 'Hexagon nut M12, stainless steel A2-70, DIN 934 standard for general assembly',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 4500,
    currency: 'IDR',
    stock_quantity: 12000,
    lead_time_days: 3,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 500,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-012',
    item_code: 'NUT-HEX-M20',
    item_name: 'MUR HEXAGON M20',
    item_description: 'Heavy hexagon nut M20, grade 10, hot-dip galvanized for structural steel connections',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 8500,
    currency: 'IDR',
    stock_quantity: 8000,
    lead_time_days: 5,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 200,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-013',
    item_code: 'ACC-WASHER-KIT',
    item_name: 'PERLENGKAPAN BAUT - Washer Kit',
    item_description: 'Flat washer assortment kit, stainless steel 304, sizes M10 to M24, 1000 pieces mixed',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 285000,
    currency: 'IDR',
    stock_quantity: 200,
    lead_time_days: 5,
    unit_of_measure: 'KIT',
    minimum_order_quantity: 5,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-014',
    item_code: 'ACC-LOCK-WASHER',
    item_name: 'PERLENGKAPAN BAUT - Lock Washer Kit',
    item_description: 'Comprehensive lock washer kit with split, star, and Nord-Lock types, 500 pieces',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 375000,
    currency: 'IDR',
    stock_quantity: 150,
    lead_time_days: 7,
    unit_of_measure: 'KIT',
    minimum_order_quantity: 5,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  },
  {
    item_id: 'ITEM-FAST-015',
    item_code: 'SCR-HEX-M8',
    item_name: 'SEKRUP HEXAGON SOCKET M8 x 40mm',
    item_description: 'Hexagon socket set screw M8 x 40mm, stainless steel A4 marine grade for panel mounting',
    category_id: 'CAT-FASTENERS',
    supplier_id: 'SUP-000007',
    unit_price: 6500,
    currency: 'IDR',
    stock_quantity: 10000,
    lead_time_days: 5,
    unit_of_measure: 'PCS',
    minimum_order_quantity: 200,
    warranty_months: 12,
    is_active: true,
    created_at: '2025-01-01T00:00:00Z',
    updated_at: '2025-01-01T00:00:00Z'
  }
];`;

console.log('Mock data expansion script completed');
console.log('Generated items array with proper structure');
