/*
  # Populate KPI Monitoring Sample Data

  1. Content
    - Sample KPI definitions across multiple categories
    - Strategic initiatives with realistic timelines
    - Sample alerts for demonstration
    - Risk and issue logs for initiatives

  2. Categories
    - Cost Efficiency
    - Delivery Performance
    - Quality Management
    - Supplier Performance
    - Inventory Optimization
    - Process Automation
*/

-- Insert sample KPIs
INSERT INTO ref_kpi (kpi_code, kpi_name, kpi_category, initiative_category, unit_of_measure, target_value, actual_value, threshold_critical, threshold_warning, threshold_target, baseline_value, timeline_start, timeline_end, frequency, data_source, calculation_method, background_issue, strategic_objective, kpi_owner, kpi_status, created_by, historical_data) VALUES

-- Cost Efficiency KPIs
('KPI-CE-001', 'Cost Savings Achievement', 'Cost Management', 'Cost Efficiency', 'IDR Million', 5000, 4250, 40, 70, 100, 0, '2024-01-01', '2024-12-31', 'Monthly', 'ERP Purchase Order Data', 'Sum of negotiated savings vs baseline prices', 'High procurement costs reducing profitability', 'Achieve 15% cost reduction through strategic sourcing', 'Supply Chain Director', 'Active', 'system', '[{"month": "Jan", "value": 350}, {"month": "Feb", "value": 420}, {"month": "Mar", "value": 480}, {"month": "Apr", "value": 520}, {"month": "May", "value": 590}, {"month": "Jun", "value": 650}, {"month": "Jul", "value": 710}, {"month": "Aug", "value": 760}, {"month": "Sep", "value": 820}, {"month": "Oct", "value": 4250}]'),

('KPI-CE-002', 'Purchase Order Cycle Time', 'Process Efficiency', 'Cost Efficiency', 'Days', 3, 3.8, 7, 5, 3, 5.2, '2024-01-01', '2024-12-31', 'Weekly', 'ERP Transaction Log', 'Average time from PR creation to PO approval', 'Long procurement cycles delaying operations', 'Reduce PO processing time to under 3 days', 'Procurement Manager', 'Active', 'system', '[{"week": 1, "value": 5.2}, {"week": 10, "value": 4.8}, {"week": 20, "value": 4.2}, {"week": 30, "value": 3.9}, {"week": 40, "value": 3.8}]'),

('KPI-CE-003', 'Contract Compliance Rate', 'Compliance', 'Cost Efficiency', 'Percentage', 95, 88, 75, 85, 95, 82, '2024-01-01', '2024-12-31', 'Monthly', 'Contract Management System', 'Percentage of POs matching contract terms', 'Off-contract spending causing cost overruns', 'Achieve 95% contract compliance rate', 'Contract Manager', 'Active', 'system', '[{"month": "Jan", "value": 82}, {"month": "Mar", "value": 84}, {"month": "Jun", "value": 86}, {"month": "Sep", "value": 88}]'),

-- Delivery Performance KPIs
('KPI-DP-001', 'On-Time Delivery Rate', 'Delivery', 'Delivery Performance', 'Percentage', 95, 91, 75, 85, 95, 87, '2024-01-01', '2024-12-31', 'Weekly', 'Goods Receipt Records', 'Percentage of deliveries within agreed schedule', 'Late deliveries causing production delays', 'Achieve 95% on-time delivery performance', 'Logistics Manager', 'Active', 'system', '[{"week": 1, "value": 87}, {"week": 10, "value": 88}, {"week": 20, "value": 89}, {"week": 30, "value": 90}, {"week": 40, "value": 91}]'),

('KPI-DP-002', 'Perfect Order Rate', 'Quality', 'Delivery Performance', 'Percentage', 98, 94, 85, 92, 98, 91, '2024-01-01', '2024-12-31', 'Monthly', 'Quality Inspection Reports', 'Orders delivered complete, on-time, damage-free', 'Order errors causing customer dissatisfaction', 'Achieve 98% perfect order rate', 'Quality Manager', 'Active', 'system', '[{"month": "Jan", "value": 91}, {"month": "Mar", "value": 92}, {"month": "Jun", "value": 93}, {"month": "Sep", "value": 94}]'),

('KPI-DP-003', 'Average Lead Time', 'Performance', 'Delivery Performance', 'Days', 12, 14.5, 20, 15, 12, 16, '2024-01-01', '2024-12-31', 'Weekly', 'Purchase Order System', 'Average time from PO to goods receipt', 'Long lead times impacting inventory planning', 'Reduce average lead time to 12 days', 'Supply Planning Manager', 'Active', 'system', '[{"week": 1, "value": 16}, {"week": 10, "value": 15.5}, {"week": 20, "value": 15}, {"week": 30, "value": 14.8}, {"week": 40, "value": 14.5}]'),

-- Quality Management KPIs
('KPI-QM-001', 'Supplier Quality Rating', 'Quality', 'Quality Management', 'Score', 4.5, 4.2, 3.0, 3.8, 4.5, 3.9, '2024-01-01', '2024-12-31', 'Monthly', 'Supplier Performance System', 'Weighted average of quality metrics', 'Quality issues causing rework and waste', 'Maintain supplier quality rating above 4.5', 'Quality Assurance Manager', 'Active', 'system', '[{"month": "Jan", "value": 3.9}, {"month": "Mar", "value": 4.0}, {"month": "Jun", "value": 4.1}, {"month": "Sep", "value": 4.2}]'),

('KPI-QM-002', 'Defect Rate', 'Quality', 'Quality Management', 'Percentage', 2, 3.2, 8, 5, 2, 4.5, '2024-01-01', '2024-12-31', 'Weekly', 'Quality Inspection Database', 'Percentage of received items with defects', 'High defect rates increasing costs', 'Reduce defect rate to under 2%', 'QC Supervisor', 'Active', 'system', '[{"week": 1, "value": 4.5}, {"week": 10, "value": 4.0}, {"week": 20, "value": 3.6}, {"week": 30, "value": 3.4}, {"week": 40, "value": 3.2}]'),

-- Supplier Performance KPIs
('KPI-SP-001', 'Supplier Responsiveness', 'Performance', 'Supplier Performance', 'Hours', 24, 28, 72, 48, 24, 36, '2024-01-01', '2024-12-31', 'Weekly', 'Communication Logs', 'Average response time to inquiries', 'Slow supplier responses delaying decisions', 'Achieve 24-hour average response time', 'Supplier Relations Manager', 'Active', 'system', '[{"week": 1, "value": 36}, {"week": 10, "value": 34}, {"week": 20, "value": 31}, {"week": 30, "value": 29}, {"week": 40, "value": 28}]'),

('KPI-SP-002', 'Supplier Consolidation', 'Strategy', 'Supplier Performance', 'Count', 50, 65, 100, 75, 50, 82, '2024-01-01', '2024-12-31', 'Quarterly', 'Vendor Master Data', 'Number of active suppliers', 'Too many suppliers increasing complexity', 'Consolidate to 50 strategic suppliers', 'Category Manager', 'Active', 'system', '[{"quarter": "Q1", "value": 82}, {"quarter": "Q2", "value": 75}, {"quarter": "Q3", "value": 68}, {"quarter": "Q4", "value": 65}]'),

-- Inventory Optimization KPIs
('KPI-IO-001', 'Inventory Turnover Ratio', 'Inventory', 'Inventory Optimization', 'Ratio', 8, 6.5, 4, 6, 8, 5.5, '2024-01-01', '2024-12-31', 'Monthly', 'Inventory Management System', 'Cost of goods sold / Average inventory', 'Excess inventory tying up capital', 'Achieve inventory turnover of 8x annually', 'Inventory Manager', 'Active', 'system', '[{"month": "Jan", "value": 5.5}, {"month": "Mar", "value": 5.8}, {"month": "Jun", "value": 6.1}, {"month": "Sep", "value": 6.5}]'),

('KPI-IO-002', 'Stock-out Rate', 'Availability', 'Inventory Optimization', 'Percentage', 1, 2.8, 8, 5, 1, 4.2, '2024-01-01', '2024-12-31', 'Weekly', 'Inventory Records', 'Percentage of stock-out incidents', 'Stock-outs causing production stoppages', 'Maintain stock-out rate below 1%', 'Materials Planning Manager', 'Active', 'system', '[{"week": 1, "value": 4.2}, {"week": 10, "value": 3.8}, {"week": 20, "value": 3.2}, {"week": 30, "value": 2.9}, {"week": 40, "value": 2.8}]'),

-- Process Automation KPIs
('KPI-PA-001', 'E-Procurement Adoption', 'Digital', 'Process Automation', 'Percentage', 90, 78, 50, 70, 90, 65, '2024-01-01', '2024-12-31', 'Monthly', 'E-Procurement System', 'Percentage of POs through e-procurement', 'Manual processes causing delays and errors', 'Achieve 90% e-procurement adoption', 'Digital Transformation Lead', 'Active', 'system', '[{"month": "Jan", "value": 65}, {"month": "Mar", "value": 70}, {"month": "Jun", "value": 74}, {"month": "Sep", "value": 78}]'),

('KPI-PA-002', 'Invoice Automation Rate', 'Automation', 'Process Automation', 'Percentage', 85, 72, 40, 60, 85, 58, '2024-01-01', '2024-12-31', 'Monthly', 'Invoice Processing System', 'Percentage of invoices processed automatically', 'Manual invoice processing causing delays', 'Achieve 85% invoice automation', 'Finance Process Manager', 'Active', 'system', '[{"month": "Jan", "value": 58}, {"month": "Mar", "value": 63}, {"month": "Jun", "value": 68}, {"month": "Sep", "value": 72}]');

-- Insert sample strategic initiatives
INSERT INTO ref_strategic_initiative (initiative_code, initiative_name, initiative_activities, initiative_category, initiative_owner, background_issue, expected_outcome, related_stakeholders, impact_estimate, impact_value, timeline_start, timeline_end, milestones, priority, initiatives_status, completion_percentage, budget_allocated, budget_spent, deliverables, success_criteria, created_by) VALUES

('INIT-001', 'Supplier Consolidation Program', 'Analyze spend data, identify strategic suppliers, negotiate new contracts, migrate to preferred vendors, decommission non-strategic suppliers', 'Supplier Performance', 'Category Director', 'High number of suppliers (82) increasing complexity, duplication, and costs. Lack of strategic partnerships limiting negotiation power.', 'Reduce active supplier base to 50 strategic partners, achieve 20% cost savings through volume consolidation, improve supplier relationship quality.', '["Procurement Team", "Finance", "Legal", "Quality", "Operations"]', '15-20% cost reduction, improved supplier quality scores by 25%', 750000000, '2024-01-15', '2024-12-31', '[{"name": "Spend Analysis Complete", "date": "2024-02-28", "status": "Completed"}, {"name": "Strategic Suppliers Identified", "date": "2024-04-30", "status": "Completed"}, {"name": "Contract Negotiations", "date": "2024-08-31", "status": "In Progress"}, {"name": "Migration Complete", "date": "2024-12-31", "status": "Pending"}]', 'High', 'In Progress', 65, 1200000000, 780000000, '["Supplier consolidation strategy", "New master supplier agreements", "Migration playbook", "Savings tracking dashboard"]', 'Reduce supplier count to 50, achieve IDR 750M savings, improve quality rating to 4.5', 'system'),

('INIT-002', 'E-Procurement Platform Implementation', 'System selection, platform configuration, user training, pilot rollout, full deployment, change management', 'Process Automation', 'Digital Transformation Lead', 'Manual procurement processes causing delays (5.2 days average), errors, and lack of visibility. No standardized workflows.', 'Implement enterprise e-procurement system with 90% adoption, reduce PO cycle time to 3 days, achieve 85% process automation.', '["IT Department", "Procurement", "Finance", "All Business Units"]', 'Reduce processing time by 40%, eliminate manual errors, save IDR 500M annually', 500000000, '2024-02-01', '2024-10-31', '[{"name": "Platform Selected", "date": "2024-03-31", "status": "Completed"}, {"name": "System Configuration", "date": "2024-06-30", "status": "Completed"}, {"name": "Pilot Rollout", "date": "2024-08-31", "status": "Completed"}, {"name": "Full Deployment", "date": "2024-10-31", "status": "In Progress"}]', 'Critical', 'In Progress', 75, 2500000000, 1875000000, '["E-procurement platform", "Training materials", "Process documentation", "Change management plan"]', 'Achieve 90% user adoption, reduce cycle time to 3 days, 85% automation rate', 'system'),

('INIT-003', 'Supplier Quality Improvement Program', 'Supplier audits, quality training, performance monitoring, corrective action plans, continuous improvement initiatives', 'Quality Management', 'Quality Assurance Director', 'High defect rate (4.5%) causing rework costs of IDR 300M annually. Supplier quality inconsistent across vendors.', 'Reduce defect rate to below 2%, improve supplier quality rating to 4.5, eliminate IDR 200M in quality costs.', '["Quality Team", "Procurement", "Suppliers", "Production", "Engineering"]', 'Reduce quality costs by 65%, improve customer satisfaction, reduce waste', 200000000, '2024-03-01', '2024-11-30', '[{"name": "Supplier Audits", "date": "2024-04-30", "status": "Completed"}, {"name": "Training Programs", "date": "2024-06-30", "status": "Completed"}, {"name": "Improvement Plans", "date": "2024-09-30", "status": "In Progress"}, {"name": "Final Assessment", "date": "2024-11-30", "status": "Pending"}]', 'High', 'In Progress', 60, 450000000, 270000000, '["Supplier audit reports", "Quality training program", "Performance scorecards", "Corrective action tracker"]', 'Defect rate below 2%, quality rating above 4.5, IDR 200M cost savings', 'system'),

('INIT-004', 'Strategic Contract Management Initiative', 'Contract repository implementation, template standardization, compliance monitoring, training program, performance tracking', 'Cost Efficiency', 'Contract Manager', 'Only 82% contract compliance causing IDR 400M in off-contract spending. No centralized contract repository.', 'Achieve 95% contract compliance, implement contract management system, save IDR 300M through better compliance.', '["Legal", "Procurement", "Finance", "Business Units"]', 'Improve compliance by 15%, reduce maverick spending, better visibility', 300000000, '2024-01-01', '2024-09-30', '[{"name": "System Implementation", "date": "2024-03-31", "status": "Completed"}, {"name": "Contract Migration", "date": "2024-06-30", "status": "Completed"}, {"name": "Training Rollout", "date": "2024-08-31", "status": "In Progress"}, {"name": "Full Compliance", "date": "2024-09-30", "status": "Pending"}]', 'High', 'In Progress', 70, 350000000, 245000000, '["Contract management system", "Standard templates", "Compliance dashboard", "Training materials"]', '95% compliance rate, IDR 300M savings, 100% contract visibility', 'system');

-- Insert sample KPI alerts
INSERT INTO kpi_alerts (kpi_id, alert_type, severity, alert_message, root_cause_analysis, actionable_recommendations, predicted_impact, alert_status, auto_generated) VALUES
((SELECT kpi_id FROM ref_kpi WHERE kpi_code = 'KPI-QM-002'), 'Threshold Breach', 'High', 'Defect Rate exceeds warning threshold at 3.2% (target: 2%)', 'Analysis shows increased defect rates from 3 key suppliers: VEN-002 (steel products), VEN-006 (ceramics), and VEN-011 (power tools). Root causes identified: inadequate incoming inspection, supplier process changes, material substitutions without approval.', '["Conduct immediate supplier audits for VEN-002, VEN-006, and VEN-011", "Implement 100% incoming inspection for these suppliers temporarily", "Review and update supplier quality agreements", "Provide quality training to supplier production teams", "Consider alternative sourcing for critical items"]', 'If defect rate continues at current level, estimated annual quality cost impact: IDR 180M. Customer complaints may increase by 15%. Production downtime risk increases.', 'Active', true),

((SELECT kpi_id FROM ref_kpi WHERE kpi_code = 'KPI-DP-003'), 'Threshold Breach', 'Medium', 'Average Lead Time increased to 14.5 days (target: 12 days)', 'Lead time analysis reveals delays in 3 areas: supplier manufacturing (40% of delay), transportation (35%), customs clearance (25%). Specific issues: capacity constraints at VEN-004 (wood supplier), port congestion in Jakarta, incomplete documentation.', '["Work with VEN-004 to increase capacity or identify backup supplier", "Review and expedite customs documentation process", "Consider air freight for critical items", "Implement lead time tracking dashboard", "Negotiate expedited shipping options with logistics providers"]', 'Extended lead times may cause stock-outs, production delays, and increased safety stock requirements (additional IDR 120M inventory holding cost).', 'Active', true),

((SELECT kpi_id FROM ref_kpi WHERE kpi_code = 'KPI-CE-003'), 'Threshold Breach', 'High', 'Contract Compliance Rate at 88%, below target of 95%', 'Off-contract spending analysis shows: 45% from urgent/emergency purchases bypassing procurement, 30% from unapproved suppliers, 25% from price variations. Main departments: Production (38%), Maintenance (35%), IT (27%).', '["Implement mandatory e-procurement for all purchases above IDR 5M", "Establish approved emergency vendor list", "Provide contract compliance training to requestors", "Enable real-time contract price checking in procurement system", "Monthly compliance review meetings with department heads"]', 'Current off-contract spending: IDR 480M annually. Achieving 95% compliance would save approximately IDR 300M through better pricing and terms.', 'Active', true),

((SELECT kpi_id FROM ref_kpi WHERE kpi_code = 'KPI-IO-002'), 'Trend Alert', 'Medium', 'Stock-out Rate trending upward, currently at 2.8% vs target of 1%', 'Stock-out trend analysis indicates: inadequate safety stock calculations (40%), inaccurate demand forecasts (35%), supplier delivery reliability issues (25%). Most affected categories: electrical components, maintenance parts, raw materials.', '["Review and update safety stock parameters", "Implement statistical forecasting for high-volume items", "Add backup suppliers for critical materials", "Increase monitoring of supplier delivery performance", "Consider vendor-managed inventory for key items"]', 'Stock-outs causing production delays averaging 8 hours per incident. Estimated lost production value: IDR 95M annually. Customer delivery delays increasing.', 'Active', true);

-- Insert sample risk logs
INSERT INTO risk_log (initiative_id, risk_code, risk_title, risk_description, risk_category, severity, likelihood, impact_description, mitigation_actions, contingency_plan, risk_owner, mitigation_deadline, risk_status, identified_date, created_by) VALUES

((SELECT initiative_id FROM ref_strategic_initiative WHERE initiative_code = 'INIT-001'), 'RISK-001', 'Supplier Resistance to Consolidation', 'Key suppliers may resist consolidation efforts or demand unfavorable contract terms, threatening timeline and savings targets. Some suppliers may refuse to participate.', 'Stakeholder', 'High', 'High', 'Could delay consolidation by 3-6 months, reduce savings target by 30-40%, and damage supplier relationships.', 'Early engagement with strategic suppliers, transparent communication of mutual benefits, phased migration approach, executive sponsorship for negotiations, consider incentive structures for suppliers.', 'If resistance continues: identify alternative suppliers, adjust consolidation targets, extend timeline by 6 months, escalate to executive steering committee.', 'Category Director', '2024-08-31', 'In Mitigation', '2024-01-20', 'system'),

((SELECT initiative_id FROM ref_strategic_initiative WHERE initiative_code = 'INIT-002'), 'RISK-002', 'Low User Adoption of E-Procurement Platform', 'Users may resist adopting new e-procurement system, preferring familiar manual processes. Risk of workarounds and system bypass.', 'Change Management', 'Critical', 'High', 'If adoption stays below 70%, ROI will not be achieved, process efficiency gains lost, and investment wasted. Estimated impact: IDR 1.5B.', 'Comprehensive change management program, hands-on training for all users, simplify user interface, provide dedicated support during rollout, gamification and incentives for early adopters, executive mandate for usage.', 'If adoption remains low: extend pilot phase, redesign problematic workflows, add more training, consider phased mandatory rollout by department.', 'Digital Transformation Lead', '2024-09-30', 'In Mitigation', '2024-02-10', 'system'),

((SELECT initiative_id FROM ref_strategic_initiative WHERE initiative_code = 'INIT-003'), 'RISK-003', 'Supplier Quality Improvement Delays', 'Suppliers may lack resources or capability to implement quality improvements quickly, causing delays in defect rate reduction.', 'Performance', 'High', 'Medium', 'Quality improvement timeline may extend by 4-6 months, defect rate reduction target may not be achieved in 2024, quality costs remain high.', 'Provide technical support to suppliers, offer joint improvement workshops, conduct regular progress reviews, establish clear milestones with accountability, consider cost-sharing for improvement investments.', 'If improvements lag: identify and qualify alternative suppliers, increase incoming inspection temporarily, adjust defect rate targets, extend program timeline.', 'Quality Assurance Director', '2024-09-30', 'Open', '2024-03-15', 'system');

-- Insert sample issue logs
INSERT INTO issue_log (initiative_id, issue_code, issue_title, issue_description, issue_category, severity, impact_description, root_cause, resolution_actions, issue_owner, resolution_deadline, issue_status, reported_date, completion_status, created_by) VALUES

((SELECT initiative_id FROM ref_strategic_initiative WHERE initiative_code = 'INIT-002'), 'ISSUE-001', 'E-Procurement System Integration Failures', 'E-procurement platform experiencing intermittent integration failures with ERP system, causing data sync issues and duplicate POs.', 'Technical', 'High', 'Creating duplicate purchase orders (15 cases), causing confusion and potential double payments. User confidence in system declining. May delay full rollout.', 'Root cause identified: API timeout issues during peak load, inadequate error handling in middleware, insufficient testing of high-volume scenarios.', 'IT team working with vendor to: 1) Optimize API performance, 2) Implement robust error handling and retry logic, 3) Add transaction logging, 4) Conduct load testing, 5) Deploy hot-fix by end of week.', 'IT Project Manager', '2024-11-15', 'In Progress', '2024-10-25', 60, 'system'),

((SELECT initiative_id FROM ref_strategic_initiative WHERE initiative_code = 'INIT-001'), 'ISSUE-002', 'Contract Negotiation Delays with Key Supplier', 'VEN-002 (steel supplier) negotiation delayed by 6 weeks due to disagreement on pricing terms and volume commitments.', 'Commercial', 'Medium', 'Consolidation timeline at risk, may miss December completion target. Current savings target reduced by IDR 85M if favorable terms not secured.', 'VEN-002 seeking 18% price increase due to raw material costs, while we target 12% reduction through volume consolidation. Gap too wide for immediate agreement.', 'Escalated to senior management for resolution. Actions: 1) Provide detailed market price analysis, 2) Propose tiered pricing based on volume, 3) Consider multi-year contract for stability, 4) Executive meeting scheduled for Nov 5, 5) Identify backup supplier as leverage.', 'Category Director', '2024-11-20', 'In Progress', '2024-10-18', 40, 'system'),

((SELECT initiative_id FROM ref_strategic_initiative WHERE initiative_code = 'INIT-004'), 'ISSUE-003', 'Incomplete Contract Data in New System', 'Only 68% of historical contracts migrated to new contract management system. Missing contracts causing compliance tracking gaps.', 'Data Quality', 'Medium', 'Incomplete compliance monitoring, users reverting to old spreadsheets, reduces system value and adoption. Compliance reporting unreliable.', 'Root cause: Legacy contracts stored in multiple locations (shared drives, emails, physical files), inconsistent naming conventions, some contracts only in hard copy, insufficient resources allocated to migration.', 'Contract admin team executing recovery plan: 1) Dedicate 2 additional staff to migration, 2) Prioritize active contracts first, 3) Conduct department-by-department contract search, 4) Digitize physical contracts, 5) Target 95% migration by Nov 30.', 'Contract Manager', '2024-11-30', 'In Progress', '2024-10-20', 68, 'system');
