/*
  # Populate Remaining Marketplace Items
  
  ## Categories:
  - Construction Materials
  - Spare Parts & Maintenance Materials
  - Safety & Environmental Equipment
  - Services
*/

-- ============================================================================
-- ITEMS: Construction Materials
-- ============================================================================

INSERT INTO marketplace_items (item_id, item_code, item_name, item_description, category_id, supplier_id, unit_price, stock_quantity, lead_time_days, unit_of_measure, technical_specifications, compliance_certifications, warranty_info) VALUES
  ('ITM-CONS-001', 'STEEL-BEAM-H400', 'Structural Steel H-Beam 400x200', 'Heavy-duty structural steel beam for construction', 'CAT-CONS', 'SUP-006', 18500000, 500, 45, 'Ton', '{"profile": "H 400x200x8x13", "grade": "SS400", "length": "12 m", "weight": "66 kg/m"}'::jsonb, '["SNI 07-0065-2002", "JIS G3101"]'::jsonb, 'Material warranty per SNI'),
  ('ITM-CONS-002', 'CONCRETE-K400', 'Ready-Mix Concrete K400', 'High-strength concrete for structural applications', 'CAT-CONS', 'SUP-006', 1250000, 10000, 7, 'M³', '{"strength": "400 kg/cm²", "slump": "12±2 cm", "max_aggregate": "25 mm", "cement_content": "400 kg/m³"}'::jsonb, '["SNI 2847:2013"]'::jsonb, '28-day strength guarantee'),
  ('ITM-CONS-003', 'PIPE-CS-SCH40-8IN', 'Carbon Steel Pipe Schedule 40', 'Seamless carbon steel pipe for steam/water lines', 'CAT-CONS', 'SUP-006', 185000, 5000, 60, 'Meter', '{"size": "8 inch", "schedule": "SCH 40", "material": "ASTM A106 Gr.B", "wall_thickness": "8.18 mm"}'::jsonb, '["ASTM A106", "ISO 9001"]'::jsonb, 'Material certificate included'),
  ('ITM-CONS-004', 'PIPE-SS-SCH40-6IN', 'Stainless Steel Pipe 316L', 'Corrosion-resistant stainless steel pipe', 'CAT-CONS', 'SUP-006', 485000, 2000, 75, 'Meter', '{"size": "6 inch", "schedule": "SCH 40", "material": "ASTM A312 TP316L", "wall_thickness": "7.11 mm"}'::jsonb, '["ASTM A312", "ISO 9001"]'::jsonb, 'Material certificate included'),
  ('ITM-CONS-005', 'INSUL-ROCKWOOL-100MM', 'Rock Wool Insulation 100mm', 'High-temperature insulation for pipes and equipment', 'CAT-CONS', 'SUP-006', 185000, 10000, 30, 'M²', '{"thickness": "100 mm", "density": "100 kg/m³", "max_temp": "750°C", "thermal_conductivity": "0.040 W/mK"}'::jsonb, '["ASTM C612", "ISO 9001"]'::jsonb, '12 months storage warranty'),
  ('ITM-CONS-006', 'FIREPROOF-BOARD-25MM', 'Fire-Resistant Board 25mm', 'Calcium silicate fire protection board', 'CAT-CONS', 'SUP-006', 285000, 5000, 45, 'M²', '{"thickness": "25 mm", "density": "650 kg/m³", "fire_rating": "A1", "max_temp": "1000°C"}'::jsonb, '["ASTM C533", "ISO 9001"]'::jsonb, '12 months'),
  ('ITM-CONS-007', 'EXP-JOINT-DN500', 'Expansion Joint DN500', 'Metal bellows expansion joint for piping', 'CAT-CONS', 'SUP-004', 28500000, 40, 90, 'Unit', '{"size": "DN500", "pressure": "PN25", "movement": "±50 mm axial", "material": "SS321", "design_temp": "400°C"}'::jsonb, '["EJMA Standards", "ISO 9001"]'::jsonb, '24 months'),
  ('ITM-CONS-008', 'CABLE-TRAY-600MM', 'Perforated Cable Tray 600mm', 'Hot-dip galvanized cable tray system', 'CAT-CONS', 'SUP-006', 485000, 2000, 30, 'Meter', '{"width": "600 mm", "height": "100 mm", "material": "Steel HDG", "loading": "Heavy Duty", "perforation": "20%"}'::jsonb, '["IEC 61537", "ISO 9001"]'::jsonb, 'Galvanizing per ASTM A123'),
  ('ITM-CONS-009', 'GRATING-STEEL-HDG', 'Steel Bar Grating Galvanized', 'Heavy-duty steel grating for platforms', 'CAT-CONS', 'SUP-006', 685000, 3000, 45, 'M²', '{"bearing_bar": "40x5 mm", "spacing": "30 mm", "cross_bar": "6 mm", "finish": "Hot-dip Galvanized"}'::jsonb, '["ASTM A1011", "ISO 9001"]'::jsonb, 'Galvanizing warranty 10 years'),
  ('ITM-CONS-010', 'ANCHOR-BOLT-M30', 'Anchor Bolt M30x600', 'High-strength anchor bolts for equipment foundation', 'CAT-CONS', 'SUP-006', 185000, 5000, 30, 'Piece', '{"diameter": "M30", "length": "600 mm", "grade": "8.8", "material": "Alloy Steel", "coating": "HDG"}'::jsonb, '["DIN 580", "ISO 9001"]'::jsonb, 'Material certificate')
ON CONFLICT (item_id) DO NOTHING;

-- ============================================================================
-- ITEMS: Spare Parts & Maintenance Materials
-- ============================================================================

INSERT INTO marketplace_items (item_id, item_code, item_name, item_description, category_id, supplier_id, unit_price, stock_quantity, lead_time_days, unit_of_measure, technical_specifications, compliance_certifications, warranty_info) VALUES
  ('ITM-SPARE-001', 'BLADE-TURBINE-ST3', 'Steam Turbine Blade Stage 3', 'Replacement turbine blade for steam turbines', 'CAT-SPARE', 'SUP-002', 285000000, 20, 120, 'Set', '{"stage": "3", "material": "12Cr Stainless Steel", "coating": "TiN", "quantity_per_set": "60 blades"}'::jsonb, '["ISO 9001", "Material Cert"]'::jsonb, '12 months operational'),
  ('ITM-SPARE-002', 'BEARING-SKF-23044', 'SKF Spherical Roller Bearing', 'Heavy-duty bearing for rotating equipment', 'CAT-SPARE', 'SUP-007', 45000000, 50, 60, 'Unit', '{"designation": "23044 CC/W33", "bore": "220 mm", "od": "340 mm", "width": "90 mm", "load_rating": "3250 kN"}'::jsonb, '["ISO 9001", "Genuine SKF"]'::jsonb, '12 months'),
  ('ITM-SPARE-003', 'GASKET-SPIRAL-DN400', 'Spiral Wound Gasket DN400', 'High-temperature spiral wound gasket', 'CAT-SPARE', 'SUP-007', 2850000, 200, 30, 'Piece', '{"size": "DN400 PN40", "material": "SS316 + Graphite", "temp_range": "-200 to 600°C", "standard": "ASME B16.20"}'::jsonb, '["ASME B16.20", "ISO 9001"]'::jsonb, 'Storage warranty 24 months'),
  ('ITM-SPARE-004', 'SEAL-MECH-65MM', 'Mechanical Seal 65mm', 'Cartridge mechanical seal for pumps', 'CAT-SPARE', 'SUP-007', 18500000, 100, 45, 'Unit', '{"shaft_size": "65 mm", "type": "Cartridge", "faces": "SiC/SiC", "temperature": "-20 to 200°C", "pressure": "25 bar"}'::jsonb, '["API 682", "ISO 9001"]'::jsonb, '12 months operational'),
  ('ITM-SPARE-005', 'OIL-TURB-ISO46', 'Turbine Oil ISO VG 46', 'Premium turbine lubricating oil', 'CAT-SPARE', 'SUP-007', 185000, 50000, 21, 'Liter', '{"viscosity": "ISO VG 46", "type": "Mineral", "additives": "Oxidation inhibitors", "standard": "ISO 8068"}'::jsonb, '["ISO 8068", "ISO 9001"]'::jsonb, '24 months unopened'),
  ('ITM-SPARE-006', 'FILTER-OIL-HF6555', 'Hydraulic Oil Filter', 'High-efficiency hydraulic filter element', 'CAT-SPARE', 'SUP-007', 2850000, 300, 30, 'Unit', '{"part_number": "HF6555", "filtration": "10 micron", "flow_rate": "380 L/min", "collapse_pressure": "30 bar"}'::jsonb, '["ISO 2941", "ISO 9001"]'::jsonb, '12 months storage'),
  ('ITM-SPARE-007', 'ELECTRODE-E7018', 'Welding Electrode E7018', 'Low-hydrogen welding electrodes', 'CAT-SPARE', 'SUP-006', 125000, 10000, 14, 'Kg', '{"classification": "E7018", "diameter": "4.0 mm", "current": "AC/DC", "position": "All positions"}'::jsonb, '["AWS A5.1", "ISO 9001"]'::jsonb, 'Storage warranty 6 months'),
  ('ITM-SPARE-008', 'BOLT-STUD-M24', 'High-Strength Stud Bolt M24', 'Alloy steel stud bolts with nuts', 'CAT-SPARE', 'SUP-006', 85000, 10000, 21, 'Set', '{"size": "M24 x 200 mm", "grade": "ASTM A193 B7", "nuts": "ASTM A194 2H", "material": "Alloy Steel"}'::jsonb, '["ASTM A193", "ISO 9001"]'::jsonb, 'Material certificate'),
  ('ITM-SPARE-009', 'CABLE-CONTROL-4C', 'Control Cable 4C x 2.5mm²', 'Instrumentation and control cable', 'CAT-SPARE', 'SUP-006', 28500, 50000, 30, 'Meter', '{"cores": "4", "conductor": "Copper 2.5mm²", "insulation": "PVC", "shielded": "Yes", "voltage": "300/500 V"}'::jsonb, '["IEC 60227", "ISO 9001"]'::jsonb, '12 months'),
  ('ITM-SPARE-010', 'COUPL-FLEX-SIZE8', 'Flexible Coupling Size 8', 'Flexible coupling for motor-pump connection', 'CAT-SPARE', 'SUP-007', 12500000, 80, 60, 'Unit', '{"size": "8", "torque": "5600 Nm", "bore": "65-80 mm", "type": "Gear coupling", "material": "Alloy Steel"}'::jsonb, '["AGMA 9002", "ISO 9001"]'::jsonb, '12 months')
ON CONFLICT (item_id) DO NOTHING;

-- ============================================================================
-- ITEMS: Safety & Environmental Equipment
-- ============================================================================

INSERT INTO marketplace_items (item_id, item_code, item_name, item_description, category_id, supplier_id, unit_price, stock_quantity, lead_time_days, unit_of_measure, technical_specifications, compliance_certifications, warranty_info) VALUES
  ('ITM-SAFE-001', 'PPE-HELMET-CLASS-E', 'Safety Helmet Class E', 'Electrical worker safety helmet', 'CAT-SAFE', 'SUP-008', 285000, 1000, 14, 'Unit', '{"type": "Class E", "voltage": "20000 V tested", "material": "HDPE", "standard": "ANSI Z89.1"}'::jsonb, '["ANSI Z89.1", "CE EN 397"]'::jsonb, '24 months manufacturing defect'),
  ('ITM-SAFE-002', 'PPE-SUIT-ARC40', 'Arc Flash Suit 40 cal/cm²', 'Full arc flash protection suit', 'CAT-SAFE', 'SUP-008', 18500000, 100, 60, 'Set', '{"arc_rating": "40 cal/cm²", "standard": "ASTM F1506", "includes": "Coat, Pants, Hood, Gloves", "color": "Dark Blue"}'::jsonb, '["ASTM F1506", "NFPA 70E", "CE"]'::jsonb, '12 months manufacturing defect'),
  ('ITM-SAFE-003', 'FD-VESDA-ASPIRATING', 'VESDA Aspirating Smoke Detector', 'Very early warning smoke detection system', 'CAT-SAFE', 'SUP-008', 85000000, 30, 90, 'Unit', '{"type": "Aspirating", "coverage": "2000 m²", "sensitivity": "0.005-20% obs/m", "response_time": "< 30 seconds"}'::jsonb, '["UL 268", "FM Approved", "CE"]'::jsonb, '24 months'),
  ('ITM-SAFE-004', 'FS-FM200-100KG', 'FM-200 Fire Suppression System', 'Clean agent fire suppression for electrical rooms', 'CAT-SAFE', 'SUP-008', 125000000, 20, 120, 'System', '{"agent": "FM-200", "capacity": "100 kg", "volume_protected": "250 m³", "discharge_time": "10 seconds"}'::jsonb, '["NFPA 2001", "ISO 14520", "CE"]'::jsonb, '36 months system, 10 years cylinder'),
  ('ITM-SAFE-005', 'EMS-CEMS-COMPLETE', 'Continuous Emission Monitoring System', 'Complete CEMS for stack emission monitoring', 'CAT-SAFE', 'SUP-009', 485000000, 5, 180, 'System', '{"parameters": "SO2, NOx, CO, CO2, O2, Opacity, Flow", "certification": "QAL1", "data_logger": "Included", "calibration": "Automatic"}'::jsonb, '["EN 15267", "EPA Method", "ISO 9001"]'::jsonb, '24 months parts and service'),
  ('ITM-SAFE-006', 'WWT-MBR-500M3', 'MBR Wastewater Treatment Plant', 'Membrane bioreactor wastewater treatment', 'CAT-SAFE', 'SUP-009', 2850000000, 2, 240, 'System', '{"capacity": "500 m³/day", "technology": "MBR", "effluent_quality": "BOD < 5 mg/L", "footprint": "300 m²"}'::jsonb, '["ISO 9001", "ISO 14001"]'::jsonb, '36 months equipment, 12 months membranes'),
  ('ITM-SAFE-007', 'AQM-STATION-AMBIENT', 'Ambient Air Quality Monitor Station', 'Multi-parameter ambient air quality monitoring', 'CAT-SAFE', 'SUP-009', 685000000, 8, 150, 'System', '{"parameters": "PM2.5, PM10, SO2, NO2, O2, CO, Meteorological", "method": "Beta Attenuation + Chemiluminescence", "data": "Real-time logging"}'::jsonb, '["ISO 9001", "ISO 17025"]'::jsonb, '24 months'),
  ('ITM-SAFE-008', 'BARRIER-SAFETY-MODULAR', 'Modular Safety Barrier System', 'Industrial safety barrier for hazardous areas', 'CAT-SAFE', 'SUP-008', 1850000, 500, 45, 'Meter', '{"height": "1.2 m", "material": "Powder-coated Steel", "mounting": "Floor/Wall", "color": "Yellow/Black"}'::jsonb, '["ISO 14120", "CE"]'::jsonb, '24 months coating warranty'),
  ('ITM-SAFE-009', 'ESD-SYSTEM-COMPLETE', 'Emergency Shutdown System', 'Complete ESD system with PLCs and valves', 'CAT-SAFE', 'SUP-004', 385000000, 10, 120, 'System', '{"sil_rating": "SIL 2", "inputs": "64 DI", "outputs": "32 DO", "valves": "8 x Shutdown valves", "redundancy": "1oo2"}'::jsonb, '["IEC 61508", "IEC 61511", "ISO 9001"]'::jsonb, '36 months'),
  ('ITM-SAFE-010', 'GAS-DETECT-H2S-4CH', 'Fixed Gas Detector H2S 4-Channel', 'Multi-channel toxic gas detection system', 'CAT-SAFE', 'SUP-008', 45000000, 40, 60, 'Unit', '{"gas": "H2S", "channels": 4, "range": "0-100 ppm", "accuracy": "±2%", "outputs": "4-20mA + Relays", "display": "LCD"}'::jsonb, '["IEC 61508", "ATEX", "CE"]'::jsonb, '24 months')
ON CONFLICT (item_id) DO NOTHING;

-- ============================================================================
-- ITEMS: Services
-- ============================================================================

INSERT INTO marketplace_items (item_id, item_code, item_name, item_description, category_id, supplier_id, unit_price, stock_quantity, lead_time_days, unit_of_measure, technical_specifications, compliance_certifications, warranty_info) VALUES
  ('ITM-SERV-001', 'SVC-PM-TURBINE-1YR', 'Preventive Maintenance Contract - Turbine', 'Annual preventive maintenance for steam turbine', 'CAT-SERV', 'SUP-010', 485000000, 50, 30, 'Contract', '{"duration": "12 months", "frequency": "Quarterly", "includes": "Labor, consumables, reports", "response_time": "24 hours"}'::jsonb, '["ISO 9001", "ISO 55001"]'::jsonb, 'Service warranty 12 months'),
  ('ITM-SERV-002', 'SVC-INSTALL-XFMR', 'Transformer Installation Service', 'Complete installation and commissioning of power transformer', 'CAT-SERV', 'SUP-010', 125000000, 100, 21, 'Service', '{"includes": "Unloading, positioning, connection, oil filling, testing, commissioning", "team_size": "8 engineers", "duration": "2 weeks"}'::jsonb, '["ISO 9001"]'::jsonb, 'Installation warranty 6 months'),
  ('ITM-SERV-003', 'SVC-COMMISSION-DCS', 'DCS Commissioning Service', 'Engineering and commissioning of control system', 'CAT-SERV', 'SUP-010', 285000000, 50, 60, 'Service', '{"includes": "Programming, testing, documentation, training", "engineers": 4, "duration": "8 weeks", "support": "30 days post"}'::jsonb, '["ISO 9001"]'::jsonb, 'Commissioning warranty 90 days'),
  ('ITM-SERV-004', 'SVC-TRAIN-OPERATOR-5D', 'Operator Training Program 5-Day', 'Comprehensive operator training for power plant', 'CAT-SERV', 'SUP-010', 85000000, 200, 45, 'Course', '{"duration": "5 days", "participants": "Up to 20", "topics": "Operations, Safety, Maintenance, Emergency", "certificate": "Included"}'::jsonb, '["ISO 9001"]'::jsonb, 'Training materials warranty 12 months'),
  ('ITM-SERV-005', 'SVC-CALIB-INSTRUMENT', 'Instrument Calibration Service', 'On-site calibration of process instruments', 'CAT-SERV', 'SUP-010', 5850000, 500, 14, 'Instrument', '{"instruments": "Pressure, Temperature, Flow, Level", "certificate": "Traceable to national standards", "report": "Detailed calibration report"}'::jsonb, '["ISO/IEC 17025", "ISO 9001"]'::jsonb, 'Calibration valid 12 months'),
  ('ITM-SERV-006', 'SVC-TEST-PERFORMANCE', 'Performance Testing Service', 'Comprehensive performance testing and optimization', 'CAT-SERV', 'SUP-010', 185000000, 100, 60, 'Service', '{"includes": "Heat rate test, efficiency test, emissions test, report", "duration": "2 weeks", "engineers": 6}'::jsonb, '["ASME PTC 6", "ISO 9001"]'::jsonb, 'Test results warranty 30 days'),
  ('ITM-SERV-007', 'SVC-MONITORING-REMOTE', 'Remote Monitoring Service 12-Month', 'Real-time remote monitoring and diagnostics', 'CAT-SERV', 'SUP-010', 285000000, 50, 30, 'Contract', '{"duration": "12 months", "monitoring": "24/7", "reports": "Monthly", "alerts": "Real-time SMS/Email", "support": "Remote troubleshooting"}'::jsonb, '["ISO 9001"]'::jsonb, 'Service warranty 12 months'),
  ('ITM-SERV-008', 'SVC-SUPPORT-TECH-24x7', 'Technical Support 24/7 Annual', 'Round-the-clock technical support hotline', 'CAT-SERV', 'SUP-010', 185000000, 100, 14, 'Contract', '{"duration": "12 months", "availability": "24/7/365", "response_time": "1 hour", "languages": "Indonesian, English", "channels": "Phone, Email, Chat"}'::jsonb, '["ISO 9001"]'::jsonb, 'Support SLA 12 months'),
  ('ITM-SERV-009', 'SVC-OVERHAUL-PUMP', 'Pump Overhaul Service', 'Complete overhaul of centrifugal pumps', 'CAT-SERV', 'SUP-010', 45000000, 200, 30, 'Service', '{"includes": "Disassembly, inspection, machining, reassembly, testing", "duration": "2 weeks", "warranty": "6 months operational"}'::jsonb, '["API 610", "ISO 9001"]'::jsonb, 'Overhaul warranty 6 months'),
  ('ITM-SERV-010', 'SVC-CONSULT-ENERGY-AUDIT', 'Energy Audit Consulting Service', 'Comprehensive energy audit and optimization recommendations', 'CAT-SERV', 'SUP-010', 125000000, 50, 45, 'Service', '{"includes": "Data collection, analysis, report, recommendations", "duration": "4 weeks", "consultants": 3, "deliverables": "Detailed report + presentation"}'::jsonb, '["ISO 50001", "ISO 9001"]'::jsonb, 'Report validity 12 months')
ON CONFLICT (item_id) DO NOTHING;
