/*
  # Create Procurement Checklist System

  1. New Tables
    - `fact_procurement_checklist`
      - Stores dynamically generated AI checklist items for sourcing events
      - Fields: id, sourcing_event_id, item_name, item_type, description, status, priority, ai_rationale, completion_date, completed_by, auto_complete_trigger, linked_document_id, organization_id

  2. Updates to Existing Tables
    - Add fields to `ref_tender_document` for checklist integration
      - source_checklist_item_id: Links document to originating checklist item
      - auto_complete_enabled: Flag indicating if approval should trigger checklist completion

  3. Security
    - Enable RLS on checklist table
    - Internal users can perform all operations
    - Add policies for authenticated access

  4. Triggers
    - Automatic checklist completion trigger when linked tender documents are approved

  5. Notes
    - Checklist items are dynamically generated by AI based on sourcing event analysis
    - Status values: Pending, In Progress, Completed, Blocked
    - Priority values: Critical, High, Medium, Low
    - Item types: Document, Approval, Validation, Compliance, Logistics
*/

-- fact_procurement_checklist table
CREATE TABLE IF NOT EXISTS fact_procurement_checklist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sourcing_event_id character varying,
  sourcing_event_line_id bigint,
  item_name text NOT NULL,
  item_type text NOT NULL DEFAULT 'Validation',
  description text,
  status text NOT NULL DEFAULT 'Pending',
  priority text NOT NULL DEFAULT 'Medium',
  ai_rationale text,
  completion_date timestamptz,
  completed_by text,
  auto_complete_trigger boolean DEFAULT false,
  linked_document_id uuid,
  assigned_to text,
  notes text,
  organization_id text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE fact_procurement_checklist ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Internal users can read all checklist items"
  ON fact_procurement_checklist FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Internal users can create checklist items"
  ON fact_procurement_checklist FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Internal users can update checklist items"
  ON fact_procurement_checklist FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Internal users can delete checklist items"
  ON fact_procurement_checklist FOR DELETE
  TO authenticated
  USING (true);

-- Add fields to ref_tender_document for checklist integration
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'ref_tender_document' AND column_name = 'source_checklist_item_id'
  ) THEN
    ALTER TABLE ref_tender_document ADD COLUMN source_checklist_item_id uuid REFERENCES fact_procurement_checklist(id);
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'ref_tender_document' AND column_name = 'auto_complete_enabled'
  ) THEN
    ALTER TABLE ref_tender_document ADD COLUMN auto_complete_enabled boolean DEFAULT true;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'ref_tender_document' AND column_name = 'document_status'
  ) THEN
    ALTER TABLE ref_tender_document ADD COLUMN document_status character varying DEFAULT 'Draft';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'ref_tender_document' AND column_name = 'approved_by'
  ) THEN
    ALTER TABLE ref_tender_document ADD COLUMN approved_by character varying;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_name = 'ref_tender_document' AND column_name = 'approved_date'
  ) THEN
    ALTER TABLE ref_tender_document ADD COLUMN approved_date timestamp;
  END IF;
END $$;

-- Create function to auto-complete checklist items when documents are approved
CREATE OR REPLACE FUNCTION auto_complete_checklist_on_document_approval()
RETURNS TRIGGER AS $$
BEGIN
  -- Check if document status changed to 'Approved' and auto_complete is enabled
  IF NEW.document_status = 'Approved' AND NEW.auto_complete_enabled = true AND NEW.source_checklist_item_id IS NOT NULL THEN
    -- Update the linked checklist item to completed
    UPDATE fact_procurement_checklist
    SET
      status = 'Completed',
      completion_date = now(),
      completed_by = NEW.approved_by,
      updated_at = now()
    WHERE id = NEW.source_checklist_item_id
      AND status != 'Completed';  -- Only update if not already completed
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger for automatic checklist completion
DROP TRIGGER IF EXISTS trigger_auto_complete_checklist ON ref_tender_document;
CREATE TRIGGER trigger_auto_complete_checklist
  AFTER UPDATE ON ref_tender_document
  FOR EACH ROW
  WHEN (NEW.document_status = 'Approved' AND OLD.document_status IS DISTINCT FROM NEW.document_status)
  EXECUTE FUNCTION auto_complete_checklist_on_document_approval();

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_checklist_sourcing_event_id ON fact_procurement_checklist(sourcing_event_id);
CREATE INDEX IF NOT EXISTS idx_checklist_sourcing_event_line_id ON fact_procurement_checklist(sourcing_event_line_id);
CREATE INDEX IF NOT EXISTS idx_checklist_status ON fact_procurement_checklist(status);
CREATE INDEX IF NOT EXISTS idx_checklist_priority ON fact_procurement_checklist(priority);
CREATE INDEX IF NOT EXISTS idx_checklist_organization ON fact_procurement_checklist(organization_id);
CREATE INDEX IF NOT EXISTS idx_tender_document_checklist_item ON ref_tender_document(source_checklist_item_id);
