/*
  # Populate Renewable Energy Tender Announcements

  1. Purpose
    - Add comprehensive dummy data for renewable energy procurement tenders
    - Demonstrate various categories: Solar, Wind, Hydro, Biomass, Geothermal, Energy Storage
    - Include realistic pricing, timelines, and material specifications

  2. Data Included
    - 15+ tender announcements with varied status and urgency levels
    - Material specifications relevant to renewable energy sector
    - Realistic Indonesian Rupiah pricing for utility-scale projects
    - Staggered deadlines to show urgency variations
    - Different project scales (small, medium, large, mega)

  3. Categories
    - Solar Energy Equipment
    - Wind Turbine Components
    - Hydroelectric Generators & Parts
    - Energy Storage Systems (Batteries)
    - Smart Grid Technology
    - Biomass Processing Equipment
    - Geothermal Components
*/

-- Insert renewable energy tender announcements
INSERT INTO fact_sourcing_event (
  sourcing_event_id,
  sourcing_event_name,
  title,
  material_id,
  material_ids,
  material_qty,
  demand_quantity,
  tender_start_date,
  tender_end_date,
  delivery_date,
  delivery_location,
  estimated_price,
  estimate_price,
  currency,
  event_status,
  status,
  approval_status,
  category,
  description,
  shortlisted_vendors,
  organization_id,
  created_at,
  updated_at
) VALUES

-- Solar Energy Tenders (High Priority)
(
  'SE-SOLAR-2024-001',
  'Solar Panel Procurement for 50 MW Power Plant',
  'Solar Panel Procurement for 50 MW Power Plant',
  'Monocrystalline Solar Panels 500W',
  '["Monocrystalline Solar Panels", "Mounting Systems", "Inverters", "Monitoring Equipment"]',
  '50,000 units',
  '50000 units',
  '2024-11-01',
  '2025-03-15',
  '2025-03-15',
  'Suralaya Power Plant, Banten',
  125000000000,
  125000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Solar',
  'Procurement of high-efficiency monocrystalline solar panels for new 50 MW solar power plant. Project includes mounting systems, inverters, and complete monitoring equipment. All equipment must meet IEC standards and include 25-year performance warranty.',
  '["PT Solar Indonesia", "PT Surya Energy", "PT Green Power Solutions"]',
  'indonesia-power',
  NOW() - INTERVAL '2 days',
  NOW()
),
(
  'SE-SOLAR-2024-002',
  'Bifacial Solar Module Supply - 100 MW Project',
  'Bifacial Solar Module Supply - 100 MW Project',
  'Bifacial Solar Modules 550W',
  '["Bifacial Solar Modules", "DC Cables", "Junction Boxes", "String Inverters"]',
  '100,000 modules',
  '100000 units',
  '2024-10-25',
  '2025-04-20',
  '2025-04-20',
  'Paiton Power Complex, East Java',
  248000000000,
  248000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Solar',
  'Large-scale procurement of bifacial solar modules for 100 MW expansion project at Paiton Complex. Requires advanced tracking systems and complete electrical balance of system. Delivery in phases over 6 months.',
  '["PT Energi Surya", "PT Panel Nusantara", "PT Solar Tech"]',
  'indonesia-power',
  NOW() - INTERVAL '5 days',
  NOW()
),
(
  'SE-SOLAR-2024-003',
  'Solar Tracking System Installation',
  'Solar Tracking System Installation',
  'Dual-Axis Solar Trackers',
  '["Dual-Axis Solar Trackers", "Control Systems", "Foundation Materials"]',
  '5,000 trackers',
  '5000 units',
  '2024-11-05',
  '2025-02-28',
  '2025-02-28',
  'Saguling Power Plant, West Java',
  45000000000,
  45000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Solar',
  'Supply and installation of dual-axis solar tracking systems to maximize energy yield. Includes control systems, structural foundations, and 15-year maintenance contract. Must withstand local wind loads and seismic requirements.',
  '["PT Tracker Solutions", "PT Solar Dynamics"]',
  'indonesia-power',
  NOW() - INTERVAL '1 day',
  NOW()
),

-- Wind Energy Tenders
(
  'SE-WIND-2024-001',
  'Wind Turbine Blade Replacement - 75 MW Wind Farm',
  'Wind Turbine Blade Replacement - 75 MW Wind Farm',
  'Wind Turbine Blades 3.0 MW',
  '["Wind Turbine Blades", "Blade Bearings", "Pitch Control Systems"]',
  '90 blades (30 sets)',
  '30 sets',
  '2024-10-20',
  '2025-05-10',
  '2025-05-10',
  'Sidrap Wind Farm, South Sulawesi',
  156000000000,
  156000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Wind',
  'Complete blade replacement for 30 wind turbines at Sidrap Wind Farm. Includes removal of existing blades, installation of new units, pitch control system upgrade, and blade balancing. Must minimize downtime during replacement.',
  '["PT Angin Energi", "PT Wind Power Indo", "PT Turbin Nusantara"]',
  'indonesia-power',
  NOW() - INTERVAL '3 days',
  NOW()
),
(
  'SE-WIND-2024-002',
  'Wind Farm SCADA System Upgrade',
  'Wind Farm SCADA System Upgrade',
  'SCADA Control Systems',
  '["SCADA Software", "Communication Hardware", "Sensors", "Data Loggers"]',
  '150 monitoring points',
  '150 units',
  '2024-10-28',
  '2025-03-30',
  '2025-03-30',
  'Jeneponto Wind Farm, South Sulawesi',
  32000000000,
  32000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Wind',
  'Comprehensive SCADA system upgrade for real-time monitoring and control of wind farm operations. Includes cybersecurity features, predictive maintenance algorithms, and integration with national grid management system.',
  '["PT Control Systems", "PT Smart Wind"]',
  'indonesia-power',
  NOW() - INTERVAL '4 days',
  NOW()
),

-- Hydroelectric Tenders
(
  'SE-HYDRO-2024-001',
  'Kaplan Turbine Overhaul - 200 MW Hydropower',
  'Kaplan Turbine Overhaul - 200 MW Hydropower',
  'Kaplan Turbine Components',
  '["Kaplan Turbine Parts", "Generator Rotors", "Wicket Gates", "Control Systems"]',
  '4 turbine sets',
  '4 sets',
  '2024-10-15',
  '2025-06-15',
  '2025-06-15',
  'Cirata Hydroelectric Plant, West Java',
  187000000000,
  187000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Hydro',
  'Major overhaul of 4 Kaplan turbines including runner replacement, generator rotor rewinding, wicket gate refurbishment, and control system modernization. Project requires specialized marine equipment and certified technicians.',
  '["PT Turbin Hydro", "PT Water Power", "PT Generator Systems"]',
  'indonesia-power',
  NOW() - INTERVAL '6 days',
  NOW()
),
(
  'SE-HYDRO-2024-002',
  'Small Hydropower Equipment - 10 MW Project',
  'Small Hydropower Equipment - 10 MW Project',
  'Francis Turbines 5 MW',
  '["Francis Turbines", "Generators", "Transformers", "Penstock Pipes"]',
  '2 turbine-generator sets',
  '2 sets',
  '2024-11-02',
  '2025-04-05',
  '2025-04-05',
  'Mrica Hydroelectric Plant, Central Java',
  42000000000,
  42000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Hydro',
  'New small hydropower installation with Francis turbines, synchronous generators, step-up transformers, and penstock system. Eco-friendly design to minimize environmental impact. Includes fish-friendly intake structures.',
  '["PT Mini Hydro", "PT Renewable Water"]',
  'indonesia-power',
  NOW() - INTERVAL '2 days',
  NOW()
),

-- Energy Storage Systems
(
  'SE-STORAGE-2024-001',
  'Lithium-Ion Battery Storage System - 100 MWh',
  'Lithium-Ion Battery Storage System - 100 MWh',
  'Li-ion Battery Storage 100 MWh',
  '["Li-ion Battery Modules", "Battery Management Systems", "Cooling Systems", "Inverters"]',
  '100 MWh capacity',
  '100 MWh',
  '2024-10-18',
  '2025-07-20',
  '2025-07-20',
  'Muara Karang Power Plant, Jakarta',
  425000000000,
  425000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Energy Storage',
  'Grid-scale lithium-ion battery energy storage system for frequency regulation and peak shaving. Includes advanced battery management, thermal cooling, fire suppression, and bidirectional inverters. 10-year performance guarantee required.',
  '["PT Battery Tech", "PT Energy Storage", "PT Power Reserve"]',
  'indonesia-power',
  NOW() - INTERVAL '1 day',
  NOW()
),
(
  'SE-STORAGE-2024-002',
  'Flow Battery System for Grid Stabilization',
  'Flow Battery System for Grid Stabilization',
  'Vanadium Flow Battery 50 MWh',
  '["Vanadium Flow Battery", "Electrolyte Solution", "Power Conversion Systems"]',
  '50 MWh capacity',
  '50 MWh',
  '2024-10-12',
  '2025-05-25',
  '2025-05-25',
  'Priok Power Plant, Jakarta',
  235000000000,
  235000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Energy Storage',
  'Vanadium redox flow battery system for long-duration energy storage and grid stabilization. Scalable design with 25-year operational life. Includes electrolyte management system and grid integration equipment.',
  '["PT Flow Energy", "PT Battery Solutions"]',
  'indonesia-power',
  NOW() - INTERVAL '7 days',
  NOW()
),

-- Smart Grid Technology
(
  'SE-SMARTGRID-2024-001',
  'Advanced Metering Infrastructure - Smart Meters',
  'Advanced Metering Infrastructure - Smart Meters',
  'Smart Electricity Meters',
  '["Smart Meters", "Communication Modules", "Data Concentrators", "Software Platform"]',
  '50,000 meters',
  '50000 units',
  '2024-10-08',
  '2025-08-10',
  '2025-08-10',
  'Java-Bali Grid Network',
  89000000000,
  89000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Smart Grid',
  'Deployment of advanced metering infrastructure across Java-Bali grid. Smart meters with remote reading, tamper detection, load management, and real-time consumption monitoring. Cloud-based data management platform included.',
  '["PT Grid Tech", "PT Smart Metering", "PT Digital Energy"]',
  'indonesia-power',
  NOW() - INTERVAL '3 days',
  NOW()
),
(
  'SE-SMARTGRID-2024-002',
  'Distribution Automation System Upgrade',
  'Distribution Automation System Upgrade',
  'Automated Distribution Equipment',
  '["Remote Terminal Units", "Automated Switches", "Voltage Regulators", "Control Software"]',
  '200 control points',
  '200 units',
  '2024-10-22',
  '2025-06-30',
  '2025-06-30',
  'Sumatra Distribution Network',
  156000000000,
  156000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Smart Grid',
  'Comprehensive distribution automation upgrade with remote terminal units, automated circuit breakers, voltage regulators, and intelligent control software. Self-healing grid capability with automatic fault isolation and restoration.',
  '["PT Automation Systems", "PT Grid Control"]',
  'indonesia-power',
  NOW() - INTERVAL '5 days',
  NOW()
),

-- Biomass Energy
(
  'SE-BIOMASS-2024-001',
  'Biomass Boiler System - 20 MW Plant',
  'Biomass Boiler System - 20 MW Plant',
  'Biomass Boiler 20 MW',
  '["Biomass Boilers", "Feeding Systems", "Ash Handling Equipment", "Emission Control"]',
  '2 boiler units',
  '2 sets',
  '2024-10-05',
  '2025-09-15',
  '2025-09-15',
  'Lampung Biomass Plant, Lampung',
  78000000000,
  78000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Biomass',
  'Complete biomass combustion system for 20 MW co-generation plant. Capable of processing various biomass feedstocks including palm oil waste, rice husk, and wood chips. Low-emission technology meeting PROPER standards.',
  '["PT Bio Energy", "PT Renewable Fuel"]',
  'indonesia-power',
  NOW() - INTERVAL '4 days',
  NOW()
),

-- Geothermal Energy
(
  'SE-GEOTHERMAL-2024-001',
  'Geothermal Wellhead Equipment',
  'Geothermal Wellhead Equipment',
  'Wellhead Valves & Separators',
  '["Wellhead Valves", "Separators", "Silencers", "Monitoring Instruments"]',
  '15 wellhead sets',
  '15 sets',
  '2024-09-28',
  '2025-10-05',
  '2025-10-05',
  'Kamojang Geothermal Field, West Java',
  134000000000,
  134000000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Geothermal',
  'Geothermal wellhead equipment for high-temperature steam production. Includes master valves, steam separators, rock catchers, silencers, and instrumentation. Must withstand 300°C operating temperature and corrosive conditions.',
  '["PT Geo Power", "PT Thermal Energy"]',
  'indonesia-power',
  NOW() - INTERVAL '6 days',
  NOW()
),

-- Urgent/Recent Tenders (Closing Soon)
(
  'SE-SOLAR-2024-004',
  'Emergency Solar Inverter Replacement',
  'Emergency Solar Inverter Replacement',
  'Central Inverters 1500 kW',
  '["Central Inverters", "Spare Parts", "Installation Services"]',
  '20 inverters',
  '20 units',
  '2024-11-01',
  '2024-11-15',
  '2024-11-15',
  'Cikarang Solar Farm, West Java',
  18500000000,
  18500000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Solar',
  'Urgent replacement of failed central inverters affecting solar farm output. Fast-track procurement with expedited delivery. Compatible with existing system architecture. Installation support and commissioning included.',
  '["PT Quick Solar", "PT Inverter Pro"]',
  'indonesia-power',
  NOW() - INTERVAL '8 days',
  NOW()
),
(
  'SE-WIND-2024-003',
  'Wind Turbine Gearbox Maintenance Kit',
  'Wind Turbine Gearbox Maintenance Kit',
  'Gearbox Components & Lubricants',
  '["Gearbox Components", "Lubricants", "Seals", "Monitoring Sensors"]',
  '10 maintenance kits',
  '10 sets',
  '2024-11-03',
  '2024-11-20',
  '2024-11-20',
  'Tolo Wind Farm, Sulawesi',
  12300000000,
  12300000000,
  'IDR',
  'Published',
  'Published',
  'Approved',
  'Wind',
  'Preventive maintenance kits for wind turbine gearboxes including replacement bearings, seals, lubricants, and condition monitoring sensors. OEM-approved parts with full warranty. Quick delivery essential to prevent production losses.',
  '["PT Wind Service", "PT Turbin Care"]',
  'indonesia-power',
  NOW() - INTERVAL '9 days',
  NOW()
);

-- Create indexes for better query performance on published tenders
CREATE INDEX IF NOT EXISTS idx_sourcing_event_published ON fact_sourcing_event(event_status, category)
WHERE event_status = 'Published';

CREATE INDEX IF NOT EXISTS idx_sourcing_event_deadline ON fact_sourcing_event(tender_end_date)
WHERE event_status = 'Published';

CREATE INDEX IF NOT EXISTS idx_sourcing_event_category ON fact_sourcing_event(category)
WHERE category IS NOT NULL;
