/*
  # Create Procurement Checklist System

  1. New Tables
    - `fact_procurement_checklist`
      - Stores dynamically generated AI checklist items for sourcing events
      - Fields: id, sourcing_event_id, item_name, item_type, description, status, priority, ai_rationale, completion_date, completed_by, auto_complete_trigger, linked_document_id, organization_id

  2. Updates to Existing Tables
    - Add fields to `ref_tender_document` for checklist integration
      - source_checklist_item_id: Links document to originating checklist item
      - auto_complete_enabled: Flag indicating if approval should trigger checklist completion

  3. Security
    - Enable RLS on checklist table
    - Internal users can perform all operations
    - Add policies for authenticated access

  4. Triggers
    - Automatic checklist completion trigger when linked tender documents are approved

  5. Notes
    - Checklist items are dynamically generated by AI based on sourcing event analysis
    - Status values: Pending, In Progress, Completed, Blocked
    - Priority values: Critical, High, Medium, Low
    - Item types: Document, Approval, Validation, Compliance, Logistics
*/

-- fact_procurement_checklist table
CREATE TABLE IF NOT EXISTS fact_procurement_checklist (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sourcing_event_id character varying,
  sourcing_event_line_id bigint,
  item_name text NOT NULL,
  item_type text NOT NULL DEFAULT 'Validation',
  description text,
  status text NOT NULL DEFAULT 'Pending',
  priority text NOT NULL DEFAULT 'Medium',
  ai_rationale text,
  completion_date timestamptz,
  completed_by text,
  auto_complete_trigger boolean DEFAULT false,
  linked_document_id uuid,
  assigned_to text,
  notes text,
  organization_id text NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

ALTER TABLE fact_procurement_checklist ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous read access to checklist"
  ON fact_procurement_checklist FOR SELECT
  USING (true);

CREATE POLICY "Allow anonymous insert access to checklist"
  ON fact_procurement_checklist FOR INSERT
  WITH CHECK (true);

CREATE POLICY "Allow anonymous update access to checklist"
  ON fact_procurement_checklist FOR UPDATE
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow anonymous delete access to checklist"
  ON fact_procurement_checklist FOR DELETE
  USING (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_checklist_sourcing_event_id ON fact_procurement_checklist(sourcing_event_id);
CREATE INDEX IF NOT EXISTS idx_checklist_sourcing_event_line_id ON fact_procurement_checklist(sourcing_event_line_id);
CREATE INDEX IF NOT EXISTS idx_checklist_status ON fact_procurement_checklist(status);
CREATE INDEX IF NOT EXISTS idx_checklist_priority ON fact_procurement_checklist(priority);
CREATE INDEX IF NOT EXISTS idx_checklist_organization ON fact_procurement_checklist(organization_id);